title: Lisa's Journal
description: This is my journal.
baseurl: "https://melissando.github.io/blog/"
url: ""
markdown: kramdown
permalink: pretty
timezone: America/Los_Angeles

plugins:
  - jekyll-feed